[package]
name = "perlin_map_generator"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.12"
image = "0.24"
noise = "0.8"
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"